import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {titleHint,titleCharacters} from './dist/hints.js';
import {MAX_GUESSES,gameStatus,restoreGame,validateLibrary} from './dist/core.js';
assert.equal(MAX_GUESSES,10);
const title='a◇7 Z あ漢字B',seed='test-round';
const initial=titleHint(title,0,seed);
assert.equal(initial.maskedTitle,'_◇_ _ 〇〇〇_');assert.equal(initial.characterCount,8);assert.equal(initial.revealedCount,0);
assert.equal(titleHint(title,2,seed).revealedCount,0);
const first=titleHint(title,3,seed),second=titleHint(title,6,seed);
assert.equal(first.revealedCount,1);assert(first.tokens.filter(t=>t.revealed).every(t=>/[漢字]/.test(t.text)));
assert.equal(titleHint(title,5,seed).revealedCount,1);assert.equal(second.revealedCount,4);
assert(second.tokens.filter(t=>t.revealed).some(t=>t.text==='あ'));assert(second.tokens.filter(t=>t.revealed).some(t=>/[ZB]/.test(t.text)));
assert(first.tokens.every((t,i)=>!t.revealed||second.tokens[i].revealed));
assert.deepEqual(second,titleHint(title,6,seed),'Reloads must never reroll hints');
assert.equal(titleHint(title,8,seed).producerUnlocked,false);assert.equal(titleHint(title,9,seed).producerUnlocked,true);
assert.equal(titleHint(title,10,seed,true).maskedTitle,title);
assert.equal(titleHint('漢A!あ7',6,seed).maskedTitle,'漢A◇あ7','Symbols are revealed after all other kinds');
assert.equal(titleHint('aAあ漢',6,seed).maskedTitle,'aAあ漢');
assert.equal(titleHint('短い',6,seed).revealedCount,2);assert.equal(titleHint(' ',6,seed).characterCount,0);
assert.equal(titleHint('T氏の話を信じるな').maskedTitle,'_〇〇〇〇〇〇〇〇');
assert.equal(titleHint('が ガ Ａ １ !').maskedTitle,'〇 〇 _ _ ◇');
assert.equal(titleCharacters('ガ👩‍🎤').length,2,'Combining marks count as one visible character');
assert(!JSON.stringify(initial).includes('漢'));assert(!JSON.stringify(initial).includes(title));
for(let i=0;i<10;i++)assert.equal(gameStatus(Array.from({length:i},(_,n)=>String(n)),'answer'),'playing');
assert.equal(gameStatus(Array.from({length:10},(_,n)=>String(n)),'answer'),'lost');
assert.equal(gameStatus([...Array.from({length:9},(_,n)=>String(n)),'answer'],'answer'),'won');
const songs=Array.from({length:11},(_,i)=>({id:String(i)}));
assert.equal(restoreGame({answerId:'10',guesses:songs.slice(0,10).map(s=>s.id)},songs,'0').guesses.length,10);
assert.deepEqual(restoreGame({answerId:'10',guesses:songs.map(s=>s.id)},songs,'0'),{answerId:'0',guesses:[]});
const valid=JSON.parse(readFileSync('dist/songs.json','utf8'));
assert.throws(()=>validateLibrary({...valid,songs:[{...valid.songs[0],title:'\u200b\u2060  '}]}));
console.log(JSON.stringify({passed:true,checks:'3/6/9 hint boundaries, character priority, count and spaces, Unicode, deterministic reload, short titles, no hidden token leakage, ten attempts and final win'}));
