import assert from'node:assert/strict';
import{readFileSync,existsSync}from'node:fs';
import{normalize,evaluate,compareNumber,compareMetric,compareViews,compareChart,compareSingers,getBeijingDate,dailyIndex,formatDuration,gameStatus,searchSongs,validateLibrary,restoreGame}from'./dist/core.js';
const library=validateLibrary(JSON.parse(readFileSync('dist/songs.json','utf8'))),songs=library.songs,find=id=>songs.find(s=>s.id===String(id));
assert.ok(songs.length>=1900);assert.ok(songs.some(s=>s.singers.includes('重音テト')));assert.ok(songs.some(s=>s.singers.includes('可不')));assert.ok(songs.some(s=>s.singers.includes('flower')));
assert.equal(searchSongs(songs,'千本樱')[0].id,'8394');assert.equal(searchSongs(songs,'senbonzakura')[0].id,'8394');assert.equal(searchSongs(songs,'rolling girl')[0].id,'1501');assert.ok(searchSongs(songs,'DECO*27').some(s=>s.id==='112085'));assert.ok(searchSongs(songs,'DECO*27').some(s=>s.title==='デビルじゃないもん'));assert.equal(searchSongs(songs,'不存在的曲目xyz').length,0);assert.equal(searchSongs(songs,'千本樱',['8394']).length,0);assert.equal(normalize('ＯＤＤＳ ＆ ＥＮＤＳ'),normalize('odds&ends'));
assert.equal(evaluate(find(8394),find(8394)).song,'exact');assert.equal(evaluate(find(1501),find(1508)).producer,'exact');assert.equal(evaluate(find(1501),find(1508)).song,'wrong');assert.equal(evaluate(find(1322),find(5166)).singers,'close');assert.equal(compareSingers(['初音未来','巡音流歌'],['巡音流歌','初音未来']),'exact');assert.equal(compareSingers(['GUMI'],['初音未来']),'wrong');
assert.deepEqual(compareNumber(2010,2012,2),{status:'close',direction:'up'});assert.deepEqual(compareNumber(2012,2010,2),{status:'close',direction:'down'});assert.equal(compareNumber(2010,2013,2).status,'wrong');assert.equal(compareNumber(200,215,15).status,'close');assert.equal(compareNumber(200,216,15).status,'wrong');assert.equal(formatDuration(246),'4:06');assert.equal(compareNumber(246,246,15).direction,null);
assert.equal(getBeijingDate(new Date('2026-10-01T15:59:59Z')),'2026-10-01');assert.equal(getBeijingDate(new Date('2026-10-01T16:00:00Z')),'2026-10-02');const index=dailyIndex('2026-10-02',library.version,songs.length);assert.equal(index,dailyIndex('2026-10-02',library.version,songs.length));assert.ok(index>=0&&index<songs.length);assert.equal(gameStatus(['8394'],'8394'),'won');assert.equal(gameStatus(songs.slice(0,10).map(s=>s.id),'8735'),'lost');assert.equal(gameStatus([],'8394'),'playing');
assert.deepEqual(restoreGame({answerId:'8394',guesses:['1501']},songs,'1322'),{answerId:'8394',guesses:['1501']});assert.deepEqual(restoreGame({answerId:'invalid',guesses:[]},songs,'1322'),{answerId:'1322',guesses:[]});assert.deepEqual(restoreGame({answerId:'8394',guesses:['1501','1501']},songs,'1322'),{answerId:'1322',guesses:[]});assert.deepEqual(restoreGame({answerId:'8394',guesses:['8394','1501']},songs,'1322'),{answerId:'1322',guesses:[]});assert.throws(()=>validateLibrary({version:'x',songs:[{}]}));
for(const song of songs){assert.equal(new URL(song.source).protocol,'https:');assert.equal(new URL(song.originalUrl).protocol,'https:');assert.ok(song.publishDate.startsWith(String(song.year)));}
const html=readFileSync('dist/index.html','utf8');for(const match of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const path=match[1];if(!/^(https?:|data:|\.\/)/.test(path))assert.ok(existsSync('dist/'+(['daily','single'].includes(path.slice(1))?path.slice(1)+'.html':path.replace(/^\//,''))),'Missing local asset '+path)}
assert.deepEqual(compareMetric(7,1,{rank:true}),{status:'wrong',direction:'up'});assert.deepEqual(compareMetric(1,7,{rank:true}),{status:'wrong',direction:'down'});
assert.equal(compareViews({status:'ok',count:0},{status:'ok',count:1}).status,'close');assert.equal(compareViews({status:'error',count:null},{status:'error',count:null}).status,'unknown');assert.equal(compareViews({status:'unlinked'},{status:'unlinked'}).status,'unknown');assert.equal(compareViews({status:'ok',count:900},{status:'ok',count:1000}).status,'close');assert.equal(compareViews({status:'ok',count:0},{status:'ok',count:0}).status,'exact');assert.equal(compareChart({status:'partial',knownWeeks:281},{status:'partial',knownWeeks:281},'weeks').status,'unknown');assert.equal(compareChart({status:'complete',weeks:0,peak:null},{status:'complete',weeks:0,peak:null},'peak').status,'exact');assert.equal(compareChart({status:'complete',weeks:0,peak:null},{status:'complete',weeks:1,peak:20},'peak').status,'wrong');
assert.equal(library.charts.billboard.from,'2022-12-07');assert.equal(library.charts.billboard.through,'2026-09-30');assert.equal(library.charts.billboard.periods,187);assert.equal(find(8394).rankings.billboard.weeks,44);assert.equal(find(164107).rankings.billboard.weeks,138);assert.equal(find(8394).rankings.weekly.knownWeeks,282);assert.equal(find(8394).rankings.weekly.status,'complete');assert.equal(find(8394).rankings.weekly.weeks,282);
const verification=JSON.parse(readFileSync('data/verification-report.json','utf8'));assert.deepEqual(verification.cumulativeMismatches,[]);
console.log(JSON.stringify({passed:true,songCount:songs.length,billboardPeriods:187,checks:'corpus, aliases, numerical and rank directions, missing versus zero, partial history, official cumulative reconciliation, Beijing rollover, round persistence, assets'}));
