import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHandler,readProvider,readNicoBatch,refreshPlayback,nicoQuery} from './server.mjs';
const read=p=>JSON.parse(readFileSync(p,'utf8')),library=read('dist/songs.json'),bundled={libraryVersion:library.version,niconico:read('data/niconico-snapshot.json'),youtube:read('data/youtube-snapshot.json')};
const handler=createHandler({'/index.html':{body:'ready',type:'text/html'}},library,bundled);
assert.equal((await handler.fetch(new Request('https://local/api/views?songs=https://evil.test'))).status,400);
assert.equal((await handler.fetch(new Request('https://local/api/views?songs='+Array(12).fill('8394').join(',')))).status,400);
assert.equal((await handler.fetch(new Request('https://local/api/views?songs=8394',{method:'POST'}))).status,405);
assert.equal((await handler.fetch(new Request('https://local/'))).status,200);
assert.equal((await handler.fetch(new Request('https://local/private'))).status,404);
assert.equal((await handler.fetch(new Request('https://local/api/refresh',{method:'POST'}))).status,403);
assert.equal((await handler.fetch(new Request('https://local/api/refresh',{method:'POST',headers:{'Content-Type':'application/json','X-Playback-Refresh':'1',Origin:'https://evil.test'}}))).status,403);
assert.throws(()=>nicoQuery(['https://evil.test']));assert.throws(()=>nicoQuery(Array(101).fill('sm1')));
const realFetch=globalThis.fetch;let calls=0;
globalThis.fetch=async(input,options)=>{calls++;const u=new URL(input);if(u.hostname==='www.googleapis.com'){assert.equal(u.searchParams.has('key'),false);assert.equal(options.headers['x-goog-api-key'],'test-only-key');return Response.json({items:u.searchParams.get('id').split(',').map(id=>({id,statistics:{viewCount:'123456'}}))});}if(u.pathname.endsWith('/version'))return Response.json({last_modified:'2026-10-04T07:00:00+09:00'});if(u.hostname==='snapshot.search.nicovideo.jp'){const ids=[...u.searchParams].filter(([k])=>k.startsWith('filters[contentId]')).map(([,v])=>v);return Response.json({meta:{status:200},data:[...ids.map(contentId=>({contentId,viewCounter:345678})),{contentId:'sm999999999',viewCounter:987654321}]});}throw Error('Unexpected upstream');};
const cacheObjects=new Map(),cacheBucket={get:async key=>cacheObjects.has(key)?{json:async()=>JSON.parse(cacheObjects.get(key))}:null,put:async(key,value)=>{cacheObjects.set(key,value);return{etag:'test-etag'}}};
const response=await handler.fetch(new Request('https://local/api/views?songs=8394,35603'),{YOUTUBE_API_KEY:'test-only-key',BUCKET:cacheBucket}),data=await response.json();
assert.ok(data.songs['8394'].niconico.count>1e6);assert.equal(data.songs['8394'].niconico.snapshotAt,bundled.niconico.snapshotAt);assert.equal(data.songs['8394'].youtube.status,'ok');assert.equal(data.niconicoCadence,'weekly');assert.equal('bilibili' in data.songs['8394'],false);
assert.equal(calls,0,'Guessing only reads stored weekly snapshots');
const retryIds=library.songs.slice(0,11).map(s=>s.id);
const retry=await handler.fetch(new Request('https://local/api/views?songs='+encodeURIComponent(retryIds.join(','))),{YOUTUBE_API_KEY:'test-only-key'});
assert.equal(retry.status,200,'Ten guesses plus their answer must fit into a retry request');assert.equal(Object.keys((await retry.json()).songs).length,11);
const rows=await readNicoBatch(['sm1'],'2026-10-04T07:00:00+09:00');assert.equal(rows.sm1.count,345678);assert.equal(rows.sm999999999,undefined);
const objects=new Map(),env={YOUTUBE_API_KEY:'test-only-key',BUCKET:{get:async key=>objects.has(key)?{json:async()=>JSON.parse(objects.get(key))}:null,put:async(key,value)=>objects.set(key,value)}};
const updated=await refreshPlayback(library,env,bundled);assert.equal(updated.niconicoSnapshotAt,'2026-10-04T07:00:00+09:00');assert.ok(updated.niconicoRecords>1900);assert.ok(objects.has('playback/latest.json'));
const pin=encodeURIComponent(bundled.niconico.snapshotAt);const pinned=await(await handler.fetch(new Request('https://local/api/views?songs=8394&snapshot='+pin),env)).json();assert.equal(pinned.songs['8394'].niconico.snapshotAt,bundled.niconico.snapshotAt);assert.equal(pinned.songs['8394'].niconico.count,bundled.niconico.records.sm15630734.count);
const prior=objects.get('playback/latest.json');globalThis.fetch=async()=>new Response('overload',{status:503});await assert.rejects(refreshPlayback(library,env,bundled,{force:true}));assert.equal(objects.get('playback/latest.json'),prior);
const fallback={count:123,snapshotAt:'2026-10-03T07:00:00+09:00',fetchedAt:'2026-10-03T00:00:00Z'};assert.equal((await readProvider('youtube',{id:'abcdefghijk',url:'https://www.youtube.com/watch?v=abcdefghijk',active:true},{YOUTUBE_API_KEY:'test-only-key'},fallback)).status,'stale');assert.equal((await readProvider('niconico',{id:'sm1234567',url:'https://www.nicovideo.jp/watch/sm1234567',active:false})).status,'unavailable');assert.equal((await readProvider('youtube',null)).status,'unlinked');
globalThis.fetch=realFetch;console.log(JSON.stringify({passed:true,checks:'daily snapshot identity, batch allowlist, persistent refresh, failure keeps prior snapshot, per-round snapshot pin, cache, platform removal, refresh CSRF boundary'}));
